version: "3.8"
services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - internal_network
      - external_network
    environment:
      - PROJECT_VERSION=0.0.1
    depends_on:
      mysql:
        condition: service_healthy

  front:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./front/nginx:/etc/nginx/conf.d
      - ./front/echoe/dist:/usr/share/nginx/html
    networks:
      - external_network
    depends_on:
      spring:
        condition: service_started

  mysql:
    image: mysql:latest
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - internal_network
    env_file:
      - ./mysql/conf.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p $$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  internal_network:
    internal: true
  external_network:
